{% set name = "sage-flatsurf" %}
{% set version = "0.7.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name | replace('-', '_') }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a2b7f04f3e481240670e9288fb6c645c8e4361eac860397fc8b2a90d05a3e471

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - sagelib
    - bidict
    - matplotlib-base
    - more-itertools
    - surface-dynamics

test:
  imports:
    - flatsurf

about:
  home: http://github.com/flatsurf/sage-flatsurf
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Flat Surfaces in SageMath
  description: |
    This module supports the investigation of geometric, algebraic and
    dynamical questions related to flat surfaces. By flat surface we mean a
    surface modeled on the plane with monodromy given by similarities of the
    plane, though current efforts are focused on translation surfaces and
    half-translation surfaces.
  doc_url: https://flatsurf.github.io/sage-flatsurf/
  dev_url: https://github.com/flatsurf/sage-flatsurf

extra:
  recipe-maintainers:
    - saraedum
    - videlec
    - slel
