{% set name = "sage-flatsurf" %}
{% set version = "0.4.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name | replace('-', '_') }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2d03e7608e4713f18663898e219852bb574cc466a6a613201bf3fccae40df816

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python =2.7|>=3.6
    - pip
  run:
    - python =2.7|>=3.6
    - sagelib
    - surface-dynamics

test:
  imports:
    - flatsurf

about:
  home: http://github.com/videlec/sage-flatsurf
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Flat Surfaces in SageMath
  description: |
    This module supports the investigation of geometric, algebraic and
    dynamical questions related to flat surfaces. By flat surface we mean a
    surface modeled on the plane with monodromy given by similarities of the
    plane, though current efforts are focused on translation surfaces and
    half-translation surfaces.
  doc_url: http://www.labri.fr/perso/vdelecro/flatsurf/latest/
  dev_url: https://github.com/videlec/sage-flatsurf

extra:
  recipe-maintainers:
    - saraedum
    - videlec
    - slel
