{% set name = "sage-flatsurf" %}
{% set version = "0.4.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name | replace('-', '_') }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6c8318a3a39b1ff5edec17cab8628674641d5becc96a15a1a9942f0576804ef1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - sagelib
    - surface-dynamics

test:
  imports:
    - flatsurf

about:
  home: http://github.com/flatsurf/sage-flatsurf
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: Flat Surfaces in SageMath
  description: |
    This module supports the investigation of geometric, algebraic and
    dynamical questions related to flat surfaces. By flat surface we mean a
    surface modeled on the plane with monodromy given by similarities of the
    plane, though current efforts are focused on translation surfaces and
    half-translation surfaces.
  doc_url: https://flatsurf.github.io/sage-flatsurf/
  dev_url: https://github.com/flatsurf/sage-flatsurf

extra:
  recipe-maintainers:
    - saraedum
    - videlec
    - slel
