travis:
  secure:
    BINSTAR_TOKEN: Ojs0ZPm2Gebc5n5ky9eQ7qeEwAuYNAs30gAfh5dOuNyqBci3QzCiF2QpcQyp0SwaWiE3W/AgbBEFyqXrjKcdZJSJjkqvuEKlwQBfsSNQvUriQjpFG4utkst7UJxDeUzjNwBQsvOsIS8AxwqZov5eJp0vL9fTi1+0QG3Hylikm1s5rIiBD2H57e5aYIbb903B+KEkK6lZLi8lY9zhEcNoODUOR7LaiXYeQ778VcqhNBUJlGx66uLJXt0f62rVeuBXrX48LZ4bh9JYQv+6X0gfS0WAgFgDO41IPcLgsNSOdh/DcRcy+n/z9fCRB7soC/bSW7OdU9ten51znRAh6L7WFUqWw8LWB7nEa6PbEQTABFPIgXqq9ei8xZlaje09zsx1q9ZKNMsyQpkN8g6wi1ghk/nFWBeldPCOhQ091/gIn9eLQnIMh44P9iAQxIBvEBkKsdrlfAIf03bs+xJ7wo7H717Jo9DR2Dod35Qh6JUbym8aADEfmGwe9l3ceqUh3aA9kqSTJLiYJCCVeIz1nEJk6biIesAX0TyRIejZ/mZDY4ZJd6InqwuQpJz4ELojWM3cuz88eaZWo5Il1QtnR9PKK4MkfveSIvnlrYmqQZRnlZ2L8kcZK1KBcvYhTm2uerbjTkGAwCsIXmep6QYA64XgPXCcp/PUKBiloe0jXu/LFs4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
